pipeline cicd modified chekout repository in runner action

diff --git a/.github/workflows/pipeline-cicd.yml b/.github/workflows/pipeline-cicd.yml
--- a/.github/workflows/pipeline-cicd.yml
+++ b/.github/workflows/pipeline-cicd.yml
@@ -225,6 +225,27 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Set up SSH key
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+
+      - name: Checkout repository
+        uses: actions/checkout@v3
+        with:
+          submodules: recursive
+          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
+      
+      - name: Validate docker-compose.yml exists
+      run: |
+        if [ ! -f ./docker-compose.yml ]; then
+          echo "Error: docker-compose.yml not found!"
+          exit 1
+        fi
+        echo "docker-compose.yml found."
+
       - name: Copy docker-compose.yml to Server
         uses: appleboy/scp-action@v0.1.3
         with:
@@ -234,7 +255,18 @@ jobs:
           key: ${{ secrets.SERVER_KEY }}
           source: ./docker-compose.yml
           target: ~/docker-compose.yml
+          run: ls -la
 
+      - name: Debug: List files on Server
+        uses: appleboy/ssh-action@v0.1.6
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USER }}
+          port: ${{ secrets.SERVER_PORT }}
+          key: ${{ secrets.SERVER_KEY }}
+          script: |
+            ls -la ~
+        
       - name: SSH to Server and Deploy
         uses: appleboy/ssh-action@v0.1.6
         with:
@@ -243,8 +275,9 @@ jobs:
           port: ${{ secrets.SERVER_PORT }}
           key: ${{ secrets.SERVER_KEY }}
           script: |
-            # Navigate to the directory with the docker-compose.yml
+            # Navigate to the directory with the docker-compose.yml and list file
             cd ~
+            ls -la ~
 
             # Pull the latest Docker images using Docker Compose
             docker-compose -f docker-compose.yml pull
